theme: jekyll-theme-minimal
title: Vincenzo Pomponi PhD
description: PhD Student, Università della Svizzera Italiana (USI)
Researcher at University of Applied Sciences and Arts of Southern Switzerland (SUPSI)
