theme: jekyll-theme-minimal
title: Vincenzo Pomponi PhD
description: PhD Student, Università della Svizzera Italiana (USI) <a href="https://www.usi.ch/en">(USI)</a>
& Researcher at University of Applied Sciences and Arts of Southern Switzerland <a href="https://www.supsi.ch/en/">(SUPSI)</a>
